//This is the array of character objects//

const characterArray = [
    {
        number: 0,
        firstName: "Boyonna",
        lastName: "Say",
        imageURL:  "resources/images/beyonce.png",
        points: 5,
        timePopUp: 5,
    },
    {
        number: 1,
        firstName: "Regina",
        lastName: "Gorge",
        imageURL: "resources/images/regina_gorge.png",
        points: 3,
        timePopUp: 5,
    },
    {
        number: 2,
        firstName: "J.Lo",
        lastName: "Glow",
        imageURL: "resources/images/JLo.png" ,
        points: 2,
        timePopUp: 5,
    },
    {
        number: 3,
        firstName: "Katy",
        lastName: "Very",
        imageURL: "resources/images/katy_very.png",
        points: 3,
        timePopUp: 5,
    },
    {
        number: 4,
        firstName: "Kim",
        lastName: "Kouture",
        imageURL: "resources/images/kim_kouture.png",
        points: 10,
        timePopUp: 5,
    },
    {
        number: 5,
        firstName: "Blake",
        lastName: "Knivey",
        imageURL: "resources/images/blake_lively.png",
        points: 3,
        timePopUp: 5,
    },
];

//this array is linked to the classes in the index.html for the location of the div//

const letterArray = ["A", "B", "C" , "D", "E", "F", "G", "H", "I"];
//these variables hold the random number and character generated by the generator functions below//

let randomCharacter = 2;


let key = "B";

//this generates a random characters identifying number//
function randomCharacterGenerator() {
    randomCharacter = Math.floor(Math.random()*characterArray.length);
    console.log(randomCharacter);
    return randomCharacter;
};


randomCharacterGenerator();

//this creates a random number to point to a location div in the html//
function randomLocationGenerator() {
    key = Math.floor(Math.random()*letterArray.length);
    key = letterArray [key];
    return key;
   ;
};
randomLocationGenerator();


console.log (document.querySelector("." +key).innerHTML)
console.log (key, randomCharacter)

switch (key, randomCharacter) {
    
    case "A":
      
        document.querySelector("." +key).innerHTML =
        "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
    
        break;
    case "B":
        document.querySelector("." +key).innerHTML =
        "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
        break;
    case "C":
        document.querySelector("." +key).innerHTML =
        "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
        break;
    case "D":
        cdocument.querySelector("." +key).innerHTML =
        "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
        break;
    case "E":
        document.querySelector("." +key).innerHTML =
        "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
        break;
    case "F":
        document.querySelector("." +key).innerHTML =
        "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
        break;
    case "G":
        document.querySelector("." +key).innerHTML =
        "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
        break;
    case "H":
        document.querySelector("." +key).innerHTML =
        "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
        break;
    case "I":
        document.querySelector("." +key).innerHTML =
        "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
        break;

    default:
        document.querySelector("." +key).innerHTML =
        "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
        break;
}

//This holds the score//

let score = 0;

//Event Listener to listen for the click of the user's mouse//


document.addEventListener("click", handleClick)



function handleClick (event) {
    const clickedElement = event.target;
    const tagName = clickedElement.tagName;
    if (tagName === 'IMG') {
        score = score + characterArray[randomCharacter].points;
        document.querySelector(".score").innerHTML = score;
        console.log (score)
        return score;
    }else
    {console.log("you lose");}
}