//This is the array of character objects//

const characterArray = [
    {
        number: 0,
        firstName: "Boyonna",
        lastName: "Say",
        imageURL:  "resources/images/beyonce.png",
        points: 5,
        timePopUp: 5,
    },
    {
        number: 1,
        firstName: "Regina",
        lastName: "Gorge",
        imageURL: "resources/images/regina_gorge.png",
        points: 3,
        timePopUp: 5,
    },
    {
        number: 2,
        firstName: "J.Lo",
        lastName: "Glow",
        imageURL: "resources/images/JLo.png" ,
        points: 2,
        timePopUp: 5,
    },
    {
        number: 3,
        firstName: "Katy",
        lastName: "Very",
        imageURL: "resources/images/katy_very.png",
        points: 3,
        timePopUp: 5,
    },
    {
        number: 4,
        firstName: "Kim",
        lastName: "Kouture",
        imageURL: "resources/images/kim_kouture.png",
        points: 10,
        timePopUp: 5,
    },
    {
        number: 5,
        firstName: "Blake",
        lastName: "Knivey",
        imageURL: "resources/images/blake_lively.png",
        points: 3,
        timePopUp: 5,
    },
];

//this array is linked to the classes in the index.html for the location of the div//

const letterArray = ["A", "B", "C" , "D", "E", "F", "G", "H", "I"];
//these variables hold the random number and character generated by the generator functions below//

let randomCharacter = null;
let score = 0;
let roundTimer = null;
let gameTimer = null;
let timeLeft =180;
let goalScore = 100;
let currentLevel = 1;
let key = "";

//this generates a random characters identifying number//

let won = true;

function randomCharacterGenerator() {
    randomCharacter = Math.floor(Math.random()*characterArray.length);
    console.log(randomCharacter);
    return randomCharacter;
};




//this creates a random number to point to a location div in the html//
function randomLocationGenerator() {
    key = Math.floor(Math.random()*letterArray.length);
    key = letterArray [key];
    return key;
   ;
};




// switch (key, randomCharacter) {
    
//     case "A":
      
//         document.querySelector("." +key).innerHTML =
//         "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
    
//         break;
//     case "B":
//         document.querySelector("." +key).innerHTML =
//         "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
//         break;
//     case "C":
//         document.querySelector("." +key).innerHTML =
//         "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
//         break;
//     case "D":
//         document.querySelector("." +key).innerHTML =
//         "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
//         break;
//     case "E":
//         document.querySelector("." +key).innerHTML =
//         "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
//         break;
//     case "F":
//         document.querySelector("." +key).innerHTML =
//         "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
//         break;
//     case "G":
//         document.querySelector("." +key).innerHTML =
//         "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
//         break;
//     case "H":
//         document.querySelector("." +key).innerHTML =
//         "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
//         break;
//     case "I":
//         document.querySelector("." +key).innerHTML =
//         "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
//         break;

//     default:
//         document.querySelector("." +key).innerHTML =
//         "<img height = '200px' src =" + characterArray[randomCharacter].imageURL +">";
//         break;
// }


//Event Listener to listen for the click of the user's mouse//


document.querySelector(".game-board").addEventListener("click", handleClick)

document.querySelector("#start").addEventListener("click", startGame);

//This function starts the game when the user clicks the start button//

function startGame() {
    score = 0;
    timeLeft = 60;
    document.querySelector(".score").textContent = score;

    startGameTimer();
    runRound();
}

function startGame() {
    clearInterval(gameTimer);
    clearTimeout(roundTimer);

    score = 0;
    timeLeft = 180;
    document.querySelector(".score").textContent = score;

    startGameTimer();
    runRound();
}

function startGameTimer() { 
    gameTimer = setInterval(() => { 
        timeLeft--; document.querySelector(".timer").innerHTML = timeLeft + " seconds"; 
        if (timeLeft <= 0) { 
            clearInterval(gameTimer); 
            clearTimeout(roundTimer); 
            endGame(); 
        } }, 1000); }
function runRound() {

    clearBoard();

    randomCharacterGenerator();
    randomLocationGenerator();

    document.querySelector("." + key).innerHTML =
        "<img height='200px' src='" + characterArray[randomCharacter].imageURL + "'>";

    // When round ends, start a new one
    roundTimer = setTimeout(() => {
        runRound();
    }, 1000); // 1 second per round — change to adjust speed
}



//This function handles the click and updates the score if the user clicks on an image//

function handleClick(event) {
    if (event.target.tagName === "IMG") {
        score += characterArray[randomCharacter].points;
        document.querySelector(".score").textContent = score;

        clearTimeout(roundTimer);
        runRound();
    }
}


function endGame() {
    clearInterval(gameTimer);
    clearTimeout(roundTimer);
    clearBoard();

    if (score >= goalScore) {
        alert("LEVEL UP! 🎉 Your score: " + score);
        nextLevel();
    } else {
        alert("Game Over! You scored " + score + ". Try again!");
    }
}

function nextLevel() {
    currentLevel++;
    goalScore += 20; // each level needs +20 more points (adjust as needed)

    timeLeft = 180; // reset 3 minute timer
    document.querySelector(".level").textContent = "Level " + currentLevel;


    startGame(); // start next level
}

function clearBoard() {
    letterArray.forEach(letter => {
        document.querySelector("." + letter).innerHTML = "";
    });
}

